// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CurrentTheme():Promise<string>;

export function CurrentVersion():Promise<string>;

export function ExportHTML(arg1:string,arg2:string):Promise<string>;

export function ExportHTMLWithDialog():Promise<string>;

export function ExportMarkdown(arg1:string):Promise<string>;

export function LoadMarkdown():Promise<main.PreviewPayload>;

export function OpenMarkdownFile():Promise<main.PreviewPayload>;

export function PrintPreview():Promise<void>;

export function SetFile(arg1:string):Promise<main.PreviewPayload>;

export function SetTheme(arg1:string):Promise<string>;
