// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentTheme() {
  return window['go']['main']['App']['CurrentTheme']();
}

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function ExportHTMLWithDialog() {
  return window['go']['main']['App']['ExportHTMLWithDialog']();
}

export function ExportMarkdown(arg1) {
  return window['go']['main']['App']['ExportMarkdown'](arg1);
}

export function LoadMarkdown() {
  return window['go']['main']['App']['LoadMarkdown']();
}

export function OpenMarkdownFile() {
  return window['go']['main']['App']['OpenMarkdownFile']();
}

export function PrintPreview() {
  return window['go']['main']['App']['PrintPreview']();
}

export function ResolveWikiLink(arg1) {
  return window['go']['main']['App']['ResolveWikiLink'](arg1);
}

export function SetFile(arg1) {
  return window['go']['main']['App']['SetFile'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
