// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function LoadMarkdown() {
  return window['go']['main']['App']['LoadMarkdown']();
}
