// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CurrentVersion():Promise<string>;

export function LoadMarkdown():Promise<main.previewPayload>;
