// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentVersion() {
  return window['go']['main']['App']['CurrentVersion']();
}

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function ExportMarkdown(arg1) {
  return window['go']['main']['App']['ExportMarkdown'](arg1);
}

export function LoadMarkdown() {
  return window['go']['main']['App']['LoadMarkdown']();
}

export function PrintPreview() {
  return window['go']['main']['App']['PrintPreview']();
}
